#!/bin/sh

vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

[ "$vol" != "${vol%\[MUTED\]}" ] && echo "muted" && exit

vol="${vol#Volume: }"

# For ommiting the . without calling and external program.
split() {
	IFS=$2
	set -- $1
	printf '%s' "$@"
}

vol="$(printf "%.0f" "$(split "$vol" ".")")"

echo "$vol%"
